### ISSUE TITLE
Switch web hosting

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#72] opened 2022-08-10 09:15 UTC
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Currently we have our previous web developer hosting the website, but he's not always very responsive, so if something went down it would be a bit of a nightmare to get in touch with him. 

**Describe the solution you'd like**
We would like to switch control of web hosting from Phil to Yalla.

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment] 2022-08-10 10:14
Hi @ShannonTrust - okay good to know. Let me speak to the rest of the team as there are a few things that would need to be organized between us for this handover. Thanks!

**Comment by cyberteenie** [comment] 2022-08-22 09:37
@thejoefriel to pick up this conversation with Phil

**Comment by thejoefriel** [comment] 2022-08-24 14:21
Yeah no worries, currently speaking to Phil about this at the moment. The work will probably take 0.5 to 1 day.

**Comment by cyberteenie** [comment] 2022-08-25 09:40
Okay, thanks @thejoefriel !

**Comment by thejoefriel** [comment] 2022-09-07 09:32
Hey @ShannonTrust starting to work on this for you. Do you mind please setting up a GreenGreeks account? 

You want the Pro account: https://www.greengeeks.com/web-hosting
For domain also put in shannontrust.org.uk 

It just needs you to enter various billing and contact details so it's best if you do this I think. 

Let me know once done and I can continue the rest of the transfer process for you

**Comment by ShannonTrust** [comment] 2022-09-09 09:06
Hi @thejoefriel, I know Chris forwarded you the login details, but adding them here as well so we have a record of everything:

Username: finance@shannontrust.org.uk
Password: 58tO393Z27

**Comment by cyberteenie** [comment] 2022-09-09 12:08
@ShannonTrust @thejoefriel - I have just deleted the comment with the password as this is an open source repository, which means that that would be public information. I know it has only been open for 3 hours, but if you could please change the password and reshare with Joe, that would probably be best. Thanks!

**Comment by ShannonTrust** [comment] 2022-09-12 08:38
Apologies, @cyberteenie. I completely forgot it was public. I've changed the password and I've just sent sent the new login details to @thejoefriel

**Comment by ShannonTrust** [comment] 2022-12-12 12:20
Hey @thejoefriel, could we have an update on where this is, please?

**Comment by thejoefriel** [comment] 2022-12-13 09:45
Hey @ShannonTrust i'm so sorry, I let this one slip with the chaos around the Turning Pages deployment. Mark ( @remaininlight ) though is working on this today and will have an update with you shortly. We will have this resolved for you 100% this week! Mark will be in touch with further updates. 

Apologies again.

**Comment by remaininlight** [comment] 2022-12-13 12:36
Hi @ShannonTrust, on this now

The hosting website has sent a code to finance@shannontrust.org.uk, please would you forward it to me at mark@yallacooperative.com so that I can get in to GreenGeeks

If you don't see this message in time then please let me know what time works for me to resend the login code

**Comment by ShannonTrust** [comment] 2022-12-13 13:44
Hi @remaininlight, sorry for the delay. I don't know how long the code lasts, but if you need to send it again I'll let my colleague know to look out for it and forward it to you

**Comment by remaininlight** [comment] 2022-12-13 15:00
Thanks @ShannonTrust, I'm in! Do you have contact details for Phil please?

**Comment by thejoefriel** [comment] 2022-12-13 15:15
@remaininlight I already forwarded you an email with his contact details. Let me know if it hasn't come through

**Comment by remaininlight** [comment] 2022-12-13 17:15
I've put in this request with GreenGeeks asking for the IPS tag:

![image](https://user-images.githubusercontent.com/4106946/207399668-30a954ec-5d1c-4c70-8ff7-7e0989d55620.png)

**Comment by remaininlight** [comment] 2022-12-22 11:36
Been chasing this around for a while, just received a definitive response from GreenGeeks:

```
Unfortunately [org.uk](http://org.uk/) Domain extension can not be transferred to us 
Here's the complete list of extensions that GreenGeeks is able to register/transfer/renew and the price for each extension:
https://www.greengeeks.com/support/article/ordering-additional-domains/
```

Looks like we may need to find another registrar

**Comment by cyberteenie** [comment] 2022-12-27 01:22
@ShannonTrust just tagging you in this thread again to make sure that you have seen Mark's comment above!

**Comment by ShannonTrust** [comment] 2023-01-03 09:08
Thanks, @remaininlight. What do you need us to do?

**Comment by remaininlight** [comment] 2023-01-04 17:06
Hi @ShannonTrust, 

I have contacted a couple of green website hosting providers (http://www.green-hosting.co.uk and https://www.guru.co.uk) about whether they support hosting .org.uk domains

There is also an option of hosting the site on AWS (where the main Turning Pages application is hosted) but this is less green

I will update you when I hear back from the hosting providers, Best,

Mark

**Comment by remaininlight** [comment] 2023-01-06 15:29
Both Green Hosting and Guru have confirmed they support hosting .org.uk domains. They are both 100% renewable energy powered, @ShannonTrust If you would like to pick whichever you prefer and make an account with them then I will prepare to transfer the domains

**Comment by ShannonTrust** [comment] 2023-01-09 08:59
Thanks, @remaininlight. We'll have a look at them and let you know soon.

**Comment by ShannonTrust** [comment] 2023-01-11 10:50
@remaininlight, we've looked into the hosting sites and we're more interested in Green Hosting, but we're unsure if they offer 24/7 support. From Yalla's point of view, does the service they offer meet the needs of our website? If the website goes down for any reason, would you be able to easily get in touch with them?

**Comment by cyberteenie** [comment] 2023-01-16 13:34
@ShannonTrust - we are just looking into this for you and will get back to you as soon as possible.

**Comment by remaininlight** [comment] 2023-01-16 14:46
@ShannonTrust The only experience I have with Green Hosting is that they answered my question about .org.uk domains very promptly, have UK based support and seem friendly

Alternatively we could host the domain on Shannon Trust's AWS account (which Turning Pages is hosted on), which has a guarantee of a support response within 24 hours

None of the other registrars I've used over the years have had particularly great support, I've asked around and received a recommendation of [hover.com](https://www.hover.com/), who apparently have good support

Let me know which option you'd like to proceed with

**Comment by ShannonTrust** [comment] 2023-01-17 15:58
@remaininlight we contacted Green Hosting and they offer a 24/7 ticketing system - they also got back to us quite quickly. With that in mind, we would like to go with Green Hosting. Do we need to set up an account with them?

**Comment by remaininlight** [comment] 2023-01-17 16:39
Brilliant, yes please @ShannonTrust. Then if you pass me the credentials by adding them to the Google doc on this issue I'll proceed with the transfer:
https://github.com/yalla-coop/shannon-trust-website/issues/1

**Comment by cyberteenie** [comment] 2023-01-23 14:54
@ShannonTrust just wanted to bump Mark's request above and ask that the credentials are added to the document in #1 so that we can get this issue done for you! Thanks!

**Comment by ShannonTrust** [comment] 2023-01-30 12:34
@remaininlight @cyberteenie We've set up the account, but now I need access to the document. Please could you accept the request - it's come from my personal account. Megan

**Comment by remaininlight** [comment] 2023-01-30 21:19
Thanks Megan (@ShannonTrust), you should now have access

**Comment by ShannonTrust** [comment] 2023-01-31 08:44
Thanks, @remaininlight. Login details have been added

**Comment by thejoefriel** [comment] 2023-02-10 16:53
Hey @ShannonTrust - thanks for adding the cpanel logins. Do you also have your green-hosting log in? I want to raise a ticket with them to get the IPS tag

**Comment by cyberteenie** [comment] 2023-02-13 12:44
@ShannonTrust just wanted to bump Joe's request for the green-hosting log in. Thanks!

**Comment by cyberteenie** [comment] 2023-02-17 10:31
Megan sent email concerning Green Hosting Account info to @thejoefriel and @cyberteenie on Feb 14

**Comment by thejoefriel** [comment] 2023-02-24 10:19
Got the IPS tag which I've now shared with Phil so I Think we're just waiting for him to push the transfer

**Comment by cyberteenie** [comment] 2023-04-17 11:28
Joe has followed up again with Phil on 12/4/23 to push the transfer

**Comment by cyberteenie** [comment] 2023-06-09 10:29
Joe to check in again with Phil next week as he still hasn't heard back.

**Comment by ShannonTrust** [comment] 2023-09-13 10:24
@thejoefriel @cyberteenie As we've not heard from Phil for a while, I've taken this issue to our CEO to see if he is able to chase him

**Comment by thejoefriel** [comment] 2023-09-13 11:58
Thanks @ShannonTrust - keep us updated.

**Comment by thejoefriel** [comment] 2024-01-29 11:28
Hey @cyberteenie sorry should have updated it here. We're currently sorting the migratoin. Alex is doing it and I'll update it once done. Should be done this week I beleive.

**Comment by cyberteenie** [comment] 2024-01-29 14:55
Ah great! Thanks for the update!

**Closed** 2024-03-18 09:43 UTC
Labels: sla, on-hold
