### ISSUE TITLE
Error message on order form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#136] opened 2024-08-12 09:47 UTC
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

I've been informed that some people have been having issues submitting orders through our online ordering form and the team have add to input orders into Salesforce manually. A message comes up saying 'oops, something went wrong' but there's no indication of why this error is happening. Could you look into why this may be, please?

### Steps To Reproduce

https://www.shannontrust.org.uk/order-resources

### Screenshots or a link to a Loom Recording

![Error message](https://github.com/user-attachments/assets/f6402487-2cd2-42a9-8796-d444468039fa)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by cyberteenie** [comment] 2024-08-12 10:15
Hi @ShannonTrust - will look into this and get back to you!

**Comment by AbdelhalimOJ** [comment] 2024-08-20 06:33
I am not able to reproduce the issue on my end, I just tried to submit the form and looks like it is working fine. it might be a case where Webflow flags some submissions as spam and they filter it so maybe we can switch this spam filtering off and see how it goes?

![image](https://github.com/user-attachments/assets/739a12c5-8bb1-4d1a-9e3c-83648b64392e)
![image](https://github.com/user-attachments/assets/8d40696e-c713-49d1-9315-57797c611128)

@cyberteenie

**Comment by ShannonTrust** [comment] 2024-08-20 10:26
Thanks for looking into this, @AbdelhalimOJ. If we can trial turning the spam filter off for now and I'll see if any other errors come up from the team.

**Comment by AbdelhalimOJ** [comment] 2024-08-20 10:38
My pleasure! I already turned it off. I hope things will go well ^^

**Comment by cyberteenie** [comment] 2024-08-27 07:26
Closing this issue for now, but feel free to reopen if needed!

**Closed by cyberteenie** 2024-08-27 07:26 UTC
Labels: bug, sla
